"""Add username and rename name to full_name

Revision ID: 1c2d9d416051
Revises: e542fd3f36e0
Create Date: 2026-02-15 08:28:52.131661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2d9d416051'
down_revision = 'e542fd3f36e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add columns as nullable
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))

    # Step 2: Migrate data
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE user SET full_name = name"))
    # Generate unique usernames for existing users
    conn.execute(sa.text("UPDATE user SET username = 'user_' || id"))

    # Step 3: Apply constraints and drop old column
    with op.batch_alter_table('user', schema=None) as batch_op:
        # SQLite constraint naming convention requires name for creates but drops might be implicit.
        # However, for batch mode, it handles recreation.
        batch_op.alter_column('username', existing_type=sa.String(length=80), nullable=False)
        batch_op.create_unique_constraint('uq_user_username', ['username'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.drop_column('full_name')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
