"""Add description and hashtags to Post model

Revision ID: b99fde46001b
Revises: 16f6b3377592
Create Date: 2026-02-08 21:36:19.124560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99fde46001b'
down_revision = '16f6b3377592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hashtags', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('hashtags')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
